### ISSUE TITLE
tests hang on Windows

### ISSUE THREAD

**Issue by chorny** [jsober/Proc-tored#1]
Tests of your module hang on Windows.
If your module cannot work on Windows at all, you can die in Makefile.PL/Build.PL. See http://wiki.cpantesters.org/wiki/CPANAuthorNotes for how to do this.

t/Proc/tored.t:
```
# Seeded srand with seed '20170215' from local date.
ok 1 - service creation {
    ok 1 - expected class
    ok 2 - expected name
    ok 3 - expected dir
    ok 4 - expected poll_wait_time
    1..4
}
(hangs)
```

**Comment by sysread** [comment]
Thank you for the report. I'll take a look first thing in the morning. 

Jeff Ober

Old programmers don't die; they just parse on...

**Comment by sysread** [comment]
I suspect this is hanging in `Proc::tored::Manager->run_lock` (https://github.com/jsober/Proc-tored/blob/master/lib/Proc/tored/Manager.pm#L213). I am suspicious of MSWin32 support for upgrading/downgrading an existing flock (e.g. switching from locally held LOCK_EX to LOCK_SH without a LOCK_UN in between).

Unfortunately, I do not have access to a Windows system for testing, so unless I am able to determine the cause I will just add a bail_out to the tests under MSWin32 in the next release.

**Comment by sysread** [comment]
Found [this](https://code.activestate.com/lists/activeperl/9783/) cave painting describing a similar situation, where Win32 failed to upgrade a LOCK_SH to LOCK_EX. Any subsequent responses were lost to erosion or possibly relic hunting nazis chasing archaeologists.

**Comment by sysread** [comment]
The root causes appear to be:
1. MSWin32 does not support upgrading/downgrading a currently held flock
2. flock on MSWin32 maps to a non-advisory lock

Because of this, `run_lock` is unable to downgrade its exclusive lock to LOCK_SH after writing its pid to the pid file. On a POSIX system, that LOCK_EX could be ignored by readers attempting to read the pid from the pid file. On MSWin32 the lack of advisory locking means that other readers will block until the LOCK_EX is released, which defeats the purpose of the pidfile.

As of 810213276141c4136b7657879fbe652027f08ef4, `run_lock` uses a secondary file created with O_EXCL to short-circuit logic that would trigger a race when two processes attempt to lock simultaneously. Only one can create the secondary file; the loser will short-circuit and not attempt to write to the pidfile.
